all:
	wget http://ftp.vim.org/vim/runtime/spell/en.latin1.spl
	wget http://ftp.vim.org/vim/runtime/spell/en.latin1.sug
	wget http://ftp.vim.org/vim/runtime/spell/en.utf-8.spl
	wget http://ftp.vim.org/vim/runtime/spell/en.utf-8.sug
	wget http://ftp.vim.org/vim/runtime/spell/fr.latin1.spl
	wget http://ftp.vim.org/vim/runtime/spell/fr.latin1.sug
	wget http://ftp.vim.org/vim/runtime/spell/fr.utf-8.spl
	wget http://ftp.vim.org/vim/runtime/spell/fr.utf-8.sug
